# filepath: /home/dapo/projects/reinsurance-app/frontend/Dockerfile
# Usa una imagen base de Nginx para servir archivos estáticos
FROM nginx:alpine

# Expone el puerto 80
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]